FROM fluidity/baseimages:focal

USER root

RUN apt-get -y update && \
      apt-get -y dist-upgrade && \
      rm -rf /var/cache/apt/archives && \
      rm -rf /var/lib/apt/lists

WORKDIR /tmp
RUN git clone -b gcc10-fixes https://github.com/fluidityproject/fluidity
WORKDIR /tmp/fluidity

RUN cp -avv . /home/fluidity
RUN chown -R fluidity /home/fluidity

USER fluidity

ENV FCFLAGS="-I/usr/include"

RUN ./configure --enable-2d-adaptivity
RUN make
RUN make fltools
