name: flow_past_a_square

on:
  workflow_dispatch:
  schedule:
    - cron: '25 03 4 * *'

jobs:
  Template:
    name: flow_past_a_square 
    runs-on: self-hosted
    timeout-minutes: 4300
    container:
      image: fluidity/baseimages:focal

    steps:

    - name: Build
      run: |
        cd /home/fluidity
        git clone https://github.com/fluidityproject/fluidity
        cd fluidity
        git clone https://github.com/fluidityproject/longtests
        export FCFLAGS="-I/usr/include"
        ./configure --enable-2d-adaptivity
        make
        make fltools

    - name: VLong Testing
      run: |
        cd /home/fluidity/fluidity
        bin/testharness -f flow_past_a_square.xml -x test_results_tides_in_the_Mediterranean_Sea.xml

    - name: JUnit
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: /home/fluidity/fluidity/test_results_flow_past_a_square.xml
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Test report flow_past_a_square
        fail_on_failure: true

