name: mphase_tephra_settling_salinity

on:
  workflow_dispatch:
  schedule:
    - cron: '25 03 14 * *'

jobs:
  Template:
    name: mphase_tephra_settling_salinity 
    runs-on: self-hosted
    timeout-minutes: 4300
    container:
      image: fluidity/baseimages:focal

    steps:

    - name: Build
      run: |
        cd /home/fluidity
        git clone https://github.com/fluidityproject/fluidity
        cd fluidity
        git clone https://github.com/fluidityproject/longtests
        export FCFLAGS="-I/usr/include"
        ./configure --enable-2d-adaptivity
        make
        make fltools

    - name: VLong Testing
      run: |
        cd /home/fluidity/fluidity
        bin/testharness -f mphase_tephra_settling_salinity.xml -x test_results_mphase_tephra_settling_salinity.xml

    - name: JUnit
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: /home/fluidity/fluidity/test_results_mphase_tephra_settling_salinity.xml
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Test report mphase_tephra_settling_salinity
        fail_on_failure: true

