name: sphere-3D-drag-Re1000

on:
  workflow_dispatch:
  schedule:
    - cron: '25 03 21 * *'

jobs:
  Template:
    name: sphere-3D-drag-Re1000 
    runs-on: self-hosted
    timeout-minutes: 4300
    container:
      image: fluidity/baseimages:focal

    steps:

    - name: Build
      run: |
        cd /home/fluidity
        git clone https://github.com/fluidityproject/fluidity
        cd fluidity
        git clone https://github.com/fluidityproject/longtests
        export FCFLAGS="-I/usr/include"
        ./configure --enable-2d-adaptivity
        make
        make fltools

    - name: VLong Testing
      run: |
        cd /home/fluidity/fluidity
        bin/testharness -f sphere-3D-drag-Re1000.xml -x test_results_sphere-3D-drag-Re1000.xml

    - name: JUnit
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: /home/fluidity/fluidity/test_results_sphere-3D-drag-Re1000.xml
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Test report sphere-3D-drag-Re1000
        fail_on_failure: true

