name: tides_in_the_Mediterranean_Sea

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 18 * *'

env:
  NAME: tides_in_the_Mediterranean_Sea

jobs:
  Template:
    name: ${NAME} 
    runs-on: self-hosted
    timeout-minutes: 4300
    container:
      image: fluidity/baseimages:focal

    steps:

    - name: Build
      run: |
        cd /home/fluidity
        git clone https://github.com/fluidityproject/fluidity
        cd fluidity
        git clone https://github.com/fluidityproject/longtests
        export FCFLAGS="-I/usr/include"
        ./configure --enable-2d-adaptivity
        make
        make fltools

    - name: VLong Testing
      run: |
        cd /home/fluidity/fluidity
        bin/testharness -f ${NAME}.xml -x test_results_${NAME}.xml

    - name: JUnit
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: /home/fluidity/fluidity/test_results_${NAME}.xml
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Test report ${NAME}
        fail_on_failure: true

